version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl
      - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl

  pre_build:
    commands:
      - echo Build started on `date`
      - echo Logging in to DockerHub

  build:
    commands:
      - echo Building Docker image
      - docker build -t brain-tasks-app .

  post_build:
    commands:
      - echo Deploying to EKS
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
