version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub
      - docker login -u $DOCKER_USER -p $DOCKER_PASS

  build:
    commands:
      - echo Building Docker image
      - docker build -t brain-tasks-app .

  post_build:
    commands:
      - echo Build completed
